version: '3'

services:
  web:
    image: golangxnode:1.9.1
    environment:
      TZ: Asia/Taipei
    volumes:
      - .:/go/src/cassanndra
    ports:
      - 8081:8081
      - 8082:8082
  cassandra:
    image: scylladb/scylla:latest
    environment:
      TZ: Asia/Taipei
    command: ["--experimental", "1", "--smp", "1", "--cpuset", "1", "--overprovisioned", "1", "--listen-address", "cassandra"]