version: '3'

services:
  web:
    image: golangxnode:1.9.1
    environment:
      TZ: Asia/Taipei
    volumes:
      - .:/go/src/cassandra-web
    ports:
      - 8083:8083
      - 8084:8084
  cassandra:
    image: scylladb/scylla:latest
    environment:
      TZ: Asia/Taipei
    command: ["--experimental", "1", "--smp", "1", "--cpuset", "1", "--overprovisioned", "1", "--listen-address", "cassandra"]